-- Seed fabricantes (~283 nombres MARCA_PROD del catálogo).
-- Prerrequisito: npm run db:manufacturers (tabla manufacturers).
-- Ejecutar: npm run db:seed-manufacturers
--
-- ON CONFLICT (name) requiere UNIQUE(name); se crea aquí de forma idempotente.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_manufacturers_name'
  ) THEN
    ALTER TABLE manufacturers
      ADD CONSTRAINT uq_manufacturers_name UNIQUE (name);
  END IF;
END $$;

INSERT INTO manufacturers (name) VALUES
  ('555'),
  ('555 JP'),
  ('A2MBPRO'),
  ('ACDC'),
  ('ACDEALER'),
  ('ACDELCO'),
  ('ALIC'),
  ('ANAM'),
  ('ANGLI'),
  ('ARTEB'),
  ('ARTICMOTORS'),
  ('ARTIMOTORS'),
  ('ARTRICA'),
  ('ASIA INC'),
  ('ATS'),
  ('AUTO 7'),
  ('AUTOMOTOR FRANCE'),
  ('AXN'),
  ('AYD'),
  ('BEARING'),
  ('BKPS'),
  ('BOSCH'),
  ('BRAKE SYSTEM'),
  ('BTB'),
  ('CABINFILTER'),
  ('CAR'),
  ('CARDOC'),
  ('CARFLEX'),
  ('CAUPLAS'),
  ('CAVALIER'),
  ('CHASIS PART'),
  ('CHERY'),
  ('CHEVROLET'),
  ('CHEVROPARTS'),
  ('CHRYSLER'),
  ('CIC'),
  ('CIC USA'),
  ('CLIPSE'),
  ('CM'),
  ('COMLINE'),
  ('CONTINENTAL'),
  ('CORTECO'),
  ('COUNA GUARD'),
  ('CT'),
  ('CTI'),
  ('CTR'),
  ('CVD'),
  ('CW AUTOMOTIVE'),
  ('CY'),
  ('DAEWHA'),
  ('DAEWOO'),
  ('DANAPAC'),
  ('DELMACK'),
  ('DELPHI'),
  ('DENSO'),
  ('DEPO'),
  ('DIAMOND'),
  ('DKING'),
  ('DLZ'),
  ('DMI'),
  ('DNI BRASIL'),
  ('DOKURO'),
  ('DOKURO JAPON'),
  ('DR.CARE'),
  ('DRIVEX'),
  ('DRIVING BELT'),
  ('DTC'),
  ('DTCO'),
  ('EAGLES POWER'),
  ('ECLIPSE'),
  ('EICA'),
  ('ENGINE'),
  ('ENGINE POWER'),
  ('ENGINE VALE'),
  ('ENGINEMOUNT'),
  ('EPDM'),
  ('EQUIPO OEM DAEWOO'),
  ('EQUIPO OEM GM'),
  ('EQUIPO OEM HYUNDAI'),
  ('EQUIPO OEM KIA'),
  ('ESP'),
  ('EUROTOP'),
  ('EXCION'),
  ('EXFIR'),
  ('FAMA'),
  ('FIAT'),
  ('FILKO'),
  ('FILTER'),
  ('FIRELOCK'),
  ('FIRST AUTOMOTIVE'),
  ('FLOAP'),
  ('FLORIO AUTOPARTS'),
  ('FNAUTO'),
  ('FOMOCO'),
  ('FORD'),
  ('FRACO'),
  ('FRENOS VEN'),
  ('FUKA'),
  ('GABRIEL'),
  ('GABRIEL MEXICO'),
  ('GABRIEL NACIONAL'),
  ('GATES'),
  ('GBI'),
  ('GENERAL ELECTRIC'),
  ('GENERAL MOTORS'),
  ('GM'),
  ('GM DAEWOO'),
  ('GM GENUINE'),
  ('GMB'),
  ('GNS'),
  ('GOMACA'),
  ('GOTO'),
  ('GRAN PRIX'),
  ('GUARDAPOLVO'),
  ('HAMMER'),
  ('HARFON'),
  ('HARRIS'),
  ('HASTING'),
  ('HINSHITSU'),
  ('HONDA'),
  ('HQP'),
  ('HSCO'),
  ('HYUNDAI'),
  ('INCOLBEST'),
  ('IND PEREZ'),
  ('INDOMAX'),
  ('INDOMAX CONTINENTAL'),
  ('INDY'),
  ('INOVOX'),
  ('INROLCA'),
  ('INTERFIL'),
  ('IRCBI'),
  ('IS3'),
  ('ISK'),
  ('ISUZU'),
  ('ISUZU GENUINE'),
  ('ITS'),
  ('JAFS'),
  ('JAGUAR'),
  ('JEEP'),
  ('JOINT SUSPENSION'),
  ('JPR'),
  ('JPS'),
  ('KANGU'),
  ('KHC'),
  ('KIA'),
  ('KIMO PREMIUM'),
  ('KING POWER'),
  ('KIOTO'),
  ('KITAKI'),
  ('KMC'),
  ('KNORR BREMSE'),
  ('KOREA'),
  ('KOSYN'),
  ('KOYO'),
  ('KURUMA'),
  ('KURUMA MEXICO'),
  ('KUSHIRO'),
  ('KYCOL'),
  ('KYOTO'),
  ('LATIN PARTES'),
  ('LATINA DE AUTOPARTES'),
  ('LATINA DE PARTES'),
  ('LIDA'),
  ('LOCTITE'),
  ('LUCAS'),
  ('LYO'),
  ('MAHLE'),
  ('MAMUSA'),
  ('MANPER'),
  ('MARILIA'),
  ('MASTER'),
  ('MASTER KING'),
  ('MASTER POWER'),
  ('MAXXUN'),
  ('MAZDA'),
  ('MCH'),
  ('MCI'),
  ('MEMO'),
  ('METALCAR'),
  ('MGM'),
  ('MHW'),
  ('MIDSUBA'),
  ('MILLARD'),
  ('MITSUBA'),
  ('MITSUBISHI'),
  ('MITSUKI'),
  ('MKM'),
  ('MONROE'),
  ('MOPAR'),
  ('MORUCH'),
  ('MOSS'),
  ('MOTORCRAFT'),
  ('MOTTA'),
  ('NATIONAL'),
  ('NATSUKI'),
  ('NGK'),
  ('NISSAN'),
  ('NOK'),
  ('NPC'),
  ('NPR'),
  ('NTK'),
  ('NTN'),
  ('ODM'),
  ('OEM'),
  ('OKAMI'),
  ('OLIMPIC'),
  ('ONNURI'),
  ('OSAP'),
  ('PANTHER'),
  ('PARTS MALL'),
  ('PBK'),
  ('PC PISTONS'),
  ('PERFECT'),
  ('PEUGEOT'),
  ('PISTON RING'),
  ('PMC'),
  ('POS'),
  ('POS ORIGINAL'),
  ('PPA'),
  ('PRECISE'),
  ('PRECISION'),
  ('PREMIUM AUTOPARTS'),
  ('PRESTOLITE'),
  ('PRO SHOCK'),
  ('PROSP3000'),
  ('QH'),
  ('QUINTON HAZELL'),
  ('RAFFKO'),
  ('RALLY'),
  ('RANALLE'),
  ('RBC'),
  ('REGITAR'),
  ('RENAULT'),
  ('RODATECH'),
  ('RTSSA'),
  ('SABO'),
  ('SAMPEL'),
  ('SANDEN'),
  ('SASUKE'),
  ('SEINECA'),
  ('SEIWA'),
  ('SGP'),
  ('SHAP'),
  ('SKF'),
  ('SKP TURQUIA'),
  ('SPICER DANA'),
  ('STEEL'),
  ('STEEL FOX'),
  ('STEELINK'),
  ('SUPERTREN'),
  ('SUZUKI'),
  ('TAIPAN'),
  ('TAMAYO'),
  ('TARANTO'),
  ('TECNIPARTS'),
  ('THOR'),
  ('TIMKEN'),
  ('TITANIUM'),
  ('TMM'),
  ('TOMCO'),
  ('TOPLINE'),
  ('TORFLEX'),
  ('TOYOTA'),
  ('TRIX'),
  ('TRW'),
  ('TRW-COVENDISA'),
  ('TVA'),
  ('TYCO'),
  ('UNION PARTS'),
  ('UNIVERSAL'),
  ('VALLEY FORGE'),
  ('VARIOS'),
  ('VEGA'),
  ('VOLKSWAGEN'),
  ('VORTEX'),
  ('WAI'),
  ('WESTAR'),
  ('WINNER'),
  ('WIX'),
  ('YAMATACHI'),
  ('YPR'),
  ('ZEN')
ON CONFLICT (name) DO NOTHING;

SELECT COUNT(*) AS total_manufacturers FROM manufacturers;
